### PR TITLE
Bump efs components

### PR DESCRIPTION
**Pull request by njuettner**
Update efs to the latest version

### CODE REVIEW

**Comment by njuettner** [comment]
From what I can see this makes `hostNetwork: true` optional but biggest impact for us it closes a lot of CVE's

**Review by whites11 — APPROVED** [review]
If host network is optional it'd be awesome to disable it.
Can we give it a try?

**Comment by njuettner** [comment]
Absolutely, I can create a cluster and see if that works 👍🏻

**Comment by njuettner** [comment]
@whites11 ok it's working now without hostNetwork 🎉, I'll update the CHANGELOG.

**Comment by whites11** [comment]
> @whites11 ok it's working now without hostNetwork tada, I'll update the CHANGELOG.

Love it, thanks!

**Review by whites11 — APPROVED** [review]

**Review by T-Kukawka — APPROVED** [review]

**Pull request merged**
